#!/bin/bash
# Gmail:
cat _site/index.html |  mail -a "Content-type: text/html" -s "Рассылка Lamoda" omegka@gmail.com

# Yandex:
cat _site/index.html |  mail -a "Content-type: text/html" -s "Рассылка Lamoda" itzamna@yandex.ru

# Outlook:
#cat _site/index.html |  mail -a "Content-type: text/html" -s "Рассылка Lamoda" itzamna@yandex.ru
